### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by AlexMetsai** [pasquale90/cpppomodoro#1]
Hi there,

Can you please add compile instructions in a README or a Makefile? You include the 'Code Blocks Project File', but I think that it would be better if they were in a more standard location.

Thanks!

**Comment by pasquale90** [comment]
Sure, I will conform with your righteous request immediately. Hopefully during this weekend.

Thanks for your kind comment!

Best Regards ,
Pasxalis

**Comment by AlexMetsai** [comment]
I see that you've added compilation instructions, good job! I'm closing the issue.
